name: weather_app
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.1 <4.0.0'

dependencies:
  cupertino_icons: # cupertino icons
  get: # for state management and context less stuff
  logger: # log events in clear way insted of (print)
  flutter_screenutil: # make app responsive
  dio: # for api requests
  http_mock_adapter: # mocking dio for testing
  pretty_dio_logger: # for dio api logging and debugging
  shared_preferences: # shared preferences persistence key value store
  location: # for location
  flutter_launcher_icons: # change app icon
  flutter_svg: # for svg icons
  smooth_page_indicator: # for onboarding screen
  carousel_slider: # for image slider
  shimmer: # for shimmer effect
  intl: # for date format
  screenshot: # for catpturing screenshots
  share_plus:
  path_provider:
  crop_your_image:
  google_maps_flutter:
  geolocator:
  geocoding:
  change_app_package_name:
  step_progress_indicator: # for progress indicator
  flutter_animate: # for animation

  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/app_icon.png"
  adaptive_icon_background: "#6151C3"
  adaptive_icon_foreground: "assets/images/app_icon_foreground.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/data/
